const { withAppBuildGradle } = require('@expo/config-plugins');

// `android/` is gitignored and fully regenerated by `expo prebuild` every time (see
// mobile/README.md), so a release signing config can't just be hand-edited into
// android/app/build.gradle - it has to be re-injected on every prebuild via this plugin instead.
//
// Adds a `release` signingConfig that's used only when the four MOBILE_RELEASE_STORE_* Gradle
// properties are present (CI sets these from GitHub secrets - see .github/workflows/create-app.yaml
// and mobile/README.md's "CI release signing" section); otherwise the release build type keeps
// signing with the debug keystore exactly as Expo's own template does, so a local
// `npx expo run:android --variant release` still works with zero extra setup.
const withAndroidReleaseSigning = (config) => {
  return withAppBuildGradle(config, (config) => {
    const { contents } = config.modResults;

    if (contents.includes('MOBILE_RELEASE_STORE_FILE')) {
      // Already applied - re-running prebuild without --clean re-invokes every plugin against an
      // already-modified file.
      return config;
    }

    const withReleaseConfig = contents.replace(
      /signingConfigs\s*\{\s*\n\s*debug\s*\{/,
      `signingConfigs {
        release {
            if (project.hasProperty('MOBILE_RELEASE_STORE_FILE')) {
                storeFile file(MOBILE_RELEASE_STORE_FILE)
                storePassword MOBILE_RELEASE_STORE_PASSWORD
                keyAlias MOBILE_RELEASE_KEY_ALIAS
                keyPassword MOBILE_RELEASE_KEY_PASSWORD
            }
        }
        debug {`
    );

    if (withReleaseConfig === contents) {
      throw new Error(
        'withAndroidReleaseSigning: signingConfigs { debug { block not found in android/app/build.gradle - the Expo template shape changed, update the regex in mobile/plugins/withAndroidReleaseSigning.js.'
      );
    }

    // Anchored on `buildTypes {` first, not just `release {` - the signingConfigs block just
    // inserted above *also* contains a `release {` (the signingConfig declaration), and a bare
    // `release {...}signingConfig signingConfigs.debug` search matches that one's nearest
    // unrelated `signingConfig signingConfigs.debug` (buildTypes.debug's, textually first in the
    // file) rather than buildTypes.release's. Scoping to after `buildTypes {` - which starts only
    // once the earlier signingConfigs block has already closed - rules that out. Non-greedy
    // [\s\S]*? (not \s*) between `release {` and the signingConfig line covers the two-line
    // "Caution! In production..." comment the template has in between.
    const withReleaseBuildType = withReleaseConfig.replace(
      /(buildTypes\s*\{[\s\S]*?release\s*\{[\s\S]*?)signingConfig signingConfigs\.debug/,
      `$1signingConfig project.hasProperty('MOBILE_RELEASE_STORE_FILE') ? signingConfigs.release : signingConfigs.debug`
    );

    if (withReleaseBuildType === withReleaseConfig) {
      throw new Error(
        "withAndroidReleaseSigning: release buildType's `signingConfig signingConfigs.debug` line not found - the Expo template shape changed, update the regex in mobile/plugins/withAndroidReleaseSigning.js."
      );
    }

    config.modResults.contents = withReleaseBuildType;
    return config;
  });
};

module.exports = withAndroidReleaseSigning;
