name: run tests
on:
  push:
    branches:
      - '*'
    paths:
      - 'ezbeq/**'
      - 'tests/**'
      - '.github/workflows/test.yaml'
  pull_request:
    branches:
      - '*'
    paths:
      - 'ezbeq/**'
      - 'tests/**'
  workflow_dispatch:
    branches:
      - '*'
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14']
        experimental: [false]
        include:
          - python-version: '3.15.0-beta.4'
            experimental: true
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: ${{ matrix.experimental }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v5
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
      - name: Install project
        run: poetry install --no-interaction
      - name: pytest
        run: |
          source .venv/bin/activate
          pytest --cov=./ezbeq --cov-report=xml
      - name: smoke test
        run: bin/smoke-test
      - name: Upload coverage to Codecov
        if: matrix.python-version == '3.14'
        uses: codecov/codecov-action@v7
        with:
          files: ./coverage.xml
