name: run tests
on:
  push:
    branches:
      - '*'
    paths:
      - 'ezbeq/**'
      - 'tests/**'
  pull_request:
    branches:
      - '*'
    paths:
      - 'ezbeq/**'
      - 'tests/**'
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install -d
          pip list
          pipenv run pip list
      - name: pytest
        run: |
          PYTHONPATH=. pipenv run pytest --cov=./ezbeq
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
