name: run tests
on:
  push:
    branches:
      - '*'
    paths:
      - 'ezbeq/**'
      - 'tests/**'
      - 'workflows/test.yaml'
  pull_request:
    branches:
      - '*'
    paths:
      - 'ezbeq/**'
      - 'tests/**'
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install -d
          pip list
          pipenv run pip list
      - name: pytest
        run: |
          PYTHONPATH=. pipenv run pytest --cov=./ezbeq --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml
